// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using proAdministration.Data.Contexts;

#nullable disable

namespace proAdministration.Data.Migrations
{
    [DbContext(typeof(CustomerContext))]
    [Migration("20240625134446_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("proAdministration.Data.Entities.Address", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.ToTable("Addresses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            City = "Bad Edgar",
                            Country = "Deutschland",
                            IsDeleted = false,
                            PostalCode = "23966",
                            State = "Rheinland-Pfalz",
                            Street = "Hohe Str. 64b"
                        },
                        new
                        {
                            Id = 2,
                            City = "Kobsdorf",
                            Country = "Deutschland",
                            IsDeleted = false,
                            PostalCode = "00532",
                            State = "Baden-Württemberg",
                            Street = "Bertha-von-Suttner-Str. 13c"
                        },
                        new
                        {
                            Id = 3,
                            City = "Bad Milo",
                            Country = "Deutschland",
                            IsDeleted = false,
                            PostalCode = "86009",
                            State = "Hessen",
                            Street = "Spandauer Str. 51"
                        },
                        new
                        {
                            Id = 4,
                            City = "Neu Thiloland",
                            Country = "Deutschland",
                            IsDeleted = false,
                            PostalCode = "53575",
                            State = "Saarland",
                            Street = "Karlstr. 0"
                        },
                        new
                        {
                            Id = 5,
                            City = "Bad Danielastadt",
                            Country = "Deutschland",
                            IsDeleted = false,
                            PostalCode = "00419",
                            State = "Thüringen",
                            Street = "Eidechsenweg 49a"
                        },
                        new
                        {
                            Id = 6,
                            City = "Thorgescheid",
                            Country = "Deutschland",
                            IsDeleted = false,
                            PostalCode = "17517",
                            State = "Mecklenburg-Vorpommern",
                            Street = "Werkstättenstr. 98c"
                        },
                        new
                        {
                            Id = 7,
                            City = "Sollerburg",
                            Country = "Deutschland",
                            IsDeleted = false,
                            PostalCode = "41848",
                            State = "Mecklenburg-Vorpommern",
                            Street = "Martin-Luther-Str. 360"
                        },
                        new
                        {
                            Id = 8,
                            City = "Süd Tarja",
                            Country = "Deutschland",
                            IsDeleted = false,
                            PostalCode = "71650",
                            State = "Brandenburg",
                            Street = "Gabriele-Münter-Str. 85"
                        },
                        new
                        {
                            Id = 9,
                            City = "Bad Susanne",
                            Country = "Deutschland",
                            IsDeleted = false,
                            PostalCode = "94812",
                            State = "Bayern",
                            Street = "Am Kemperstiegel 2"
                        },
                        new
                        {
                            Id = 10,
                            City = "Süd Jonathan",
                            Country = "Deutschland",
                            IsDeleted = false,
                            PostalCode = "25692",
                            State = "Thüringen",
                            Street = "Paulstr. 72b"
                        },
                        new
                        {
                            Id = 11,
                            City = "Wesseldorf",
                            Country = "Deutschland",
                            IsDeleted = false,
                            PostalCode = "01169",
                            State = "Hamburg",
                            Street = "Hermann-von-Helmholtz-Str. 11c"
                        },
                        new
                        {
                            Id = 12,
                            City = "Süd Jenna",
                            Country = "Deutschland",
                            IsDeleted = false,
                            PostalCode = "87359",
                            State = "Berlin",
                            Street = "Bensberger Str. 602"
                        },
                        new
                        {
                            Id = 13,
                            City = "Tamialand",
                            Country = "Deutschland",
                            IsDeleted = false,
                            PostalCode = "65201",
                            State = "Bayern",
                            Street = "Schulstr. 09"
                        },
                        new
                        {
                            Id = 14,
                            City = "Süd Joelleland",
                            Country = "Deutschland",
                            IsDeleted = false,
                            PostalCode = "27777",
                            State = "Nordrhein-Westfalen",
                            Street = "Kapellenstr. 57a"
                        },
                        new
                        {
                            Id = 15,
                            City = "Tarjaburg",
                            Country = "Deutschland",
                            IsDeleted = false,
                            PostalCode = "19243",
                            State = "Sachsen",
                            Street = "Dünnwalder Grenzweg 96b"
                        },
                        new
                        {
                            Id = 16,
                            City = "Süd Susannestadt",
                            Country = "Deutschland",
                            IsDeleted = false,
                            PostalCode = "67105",
                            State = "Bayern",
                            Street = "Weichselstr. 45c"
                        },
                        new
                        {
                            Id = 17,
                            City = "Thaliastadt",
                            Country = "Deutschland",
                            IsDeleted = false,
                            PostalCode = "73386",
                            State = "Niedersachsen",
                            Street = "Maria-Dresen-Str. 84"
                        },
                        new
                        {
                            Id = 18,
                            City = "Bad Tyron",
                            Country = "Deutschland",
                            IsDeleted = false,
                            PostalCode = "55085",
                            State = "Brandenburg",
                            Street = "Friedrich-Naumann-Str. 3"
                        },
                        new
                        {
                            Id = 19,
                            City = "Bad Matteo",
                            Country = "Deutschland",
                            IsDeleted = false,
                            PostalCode = "36328",
                            State = "Bremen",
                            Street = "Am Hagelkreuz 71a"
                        },
                        new
                        {
                            Id = 20,
                            City = "Krohnland",
                            Country = "Deutschland",
                            IsDeleted = false,
                            PostalCode = "03895",
                            State = "Rheinland-Pfalz",
                            Street = "Ottweilerstr. 20b"
                        },
                        new
                        {
                            Id = 21,
                            City = "Matulastadt",
                            Country = "Deutschland",
                            IsDeleted = false,
                            PostalCode = "03616",
                            State = "Sachsen",
                            Street = "Helmestr. 693"
                        },
                        new
                        {
                            Id = 22,
                            City = "Krugerscheid",
                            Country = "Deutschland",
                            IsDeleted = false,
                            PostalCode = "67937",
                            State = "Hessen",
                            Street = "Bahnhofstr. 17"
                        },
                        new
                        {
                            Id = 23,
                            City = "Jonaburg",
                            Country = "Deutschland",
                            IsDeleted = false,
                            PostalCode = "24440",
                            State = "Sachsen-Anhalt",
                            Street = "Schloßstr. 5"
                        },
                        new
                        {
                            Id = 24,
                            City = "Williburg",
                            Country = "Deutschland",
                            IsDeleted = false,
                            PostalCode = "21970",
                            State = "Bayern",
                            Street = "Kaiserplatz 05b"
                        },
                        new
                        {
                            Id = 25,
                            City = "Bad Collinland",
                            Country = "Deutschland",
                            IsDeleted = false,
                            PostalCode = "84463",
                            State = "Saarland",
                            Street = "Dönhoffstr. 44c"
                        },
                        new
                        {
                            Id = 26,
                            City = "Ost Medine",
                            Country = "Deutschland",
                            IsDeleted = false,
                            PostalCode = "59127",
                            State = "Mecklenburg-Vorpommern",
                            Street = "Von-Siebold-Str. 925"
                        },
                        new
                        {
                            Id = 27,
                            City = "Bad Markodorf",
                            Country = "Deutschland",
                            IsDeleted = false,
                            PostalCode = "15882",
                            State = "Berlin",
                            Street = "Ludwig-Girtler-Str. 31"
                        },
                        new
                        {
                            Id = 28,
                            City = "Süd Tammo",
                            Country = "Deutschland",
                            IsDeleted = false,
                            PostalCode = "38055",
                            State = "Nordrhein-Westfalen",
                            Street = "Friedensstr. 80a"
                        },
                        new
                        {
                            Id = 29,
                            City = "Zeyenland",
                            Country = "Deutschland",
                            IsDeleted = false,
                            PostalCode = "15521",
                            State = "Thüringen",
                            Street = "Am Borsberg 29b"
                        },
                        new
                        {
                            Id = 30,
                            City = "Süd Jana",
                            Country = "Deutschland",
                            IsDeleted = false,
                            PostalCode = "82097",
                            State = "Hamburg",
                            Street = "Oststr. 77c"
                        },
                        new
                        {
                            Id = 31,
                            City = "Zinserburg",
                            Country = "Deutschland",
                            IsDeleted = false,
                            PostalCode = "69563",
                            State = "Saarland",
                            Street = "Heinrich-Heine-Str. 26"
                        },
                        new
                        {
                            Id = 32,
                            City = "Kilianland",
                            Country = "Deutschland",
                            IsDeleted = false,
                            PostalCode = "84613",
                            State = "Schleswig-Holstein",
                            Street = "Auf den Reien 6"
                        },
                        new
                        {
                            Id = 33,
                            City = "Zoestadt",
                            Country = "Deutschland",
                            IsDeleted = false,
                            PostalCode = "23606",
                            State = "Mecklenburg-Vorpommern",
                            Street = "Schellingstr. 13a"
                        },
                        new
                        {
                            Id = 34,
                            City = "Süd Jannisburg",
                            Country = "Deutschland",
                            IsDeleted = false,
                            PostalCode = "01721",
                            State = "Hamburg",
                            Street = "Johannes-Dott-Str. 52b"
                        },
                        new
                        {
                            Id = 35,
                            City = "West Janisstadt",
                            Country = "Deutschland",
                            IsDeleted = false,
                            PostalCode = "64856",
                            State = "Sachsen",
                            Street = "Dhünnberg 015"
                        },
                        new
                        {
                            Id = 36,
                            City = "Süd Sinanland",
                            Country = "Deutschland",
                            IsDeleted = false,
                            PostalCode = "31159",
                            State = "Sachsen-Anhalt",
                            Street = "Virchowstr. 40"
                        },
                        new
                        {
                            Id = 37,
                            City = "Kuhleestadt",
                            Country = "Deutschland",
                            IsDeleted = false,
                            PostalCode = "53078",
                            State = "Niedersachsen",
                            Street = "Löfflerstr. 9"
                        },
                        new
                        {
                            Id = 38,
                            City = "Küterscheid",
                            Country = "Deutschland",
                            IsDeleted = false,
                            PostalCode = "17257",
                            State = "Bremen",
                            Street = "Franz-Esser-Str. 37b"
                        },
                        new
                        {
                            Id = 39,
                            City = "Nord Lola",
                            Country = "Deutschland",
                            IsDeleted = false,
                            PostalCode = "94723",
                            State = "Rheinland-Pfalz",
                            Street = "Altenberger Str. 86c"
                        },
                        new
                        {
                            Id = 40,
                            City = "Sabrinastadt",
                            Country = "Deutschland",
                            IsDeleted = false,
                            PostalCode = "12906",
                            State = "Sachsen",
                            Street = "Odenthaler Str. 258"
                        },
                        new
                        {
                            Id = 41,
                            City = "Nord Boris",
                            Country = "Deutschland",
                            IsDeleted = false,
                            PostalCode = "48766",
                            State = "Hessen",
                            Street = "Hebbelstr. 73"
                        },
                        new
                        {
                            Id = 42,
                            City = "Alicestadt",
                            Country = "Deutschland",
                            IsDeleted = false,
                            PostalCode = "25332",
                            State = "Sachsen",
                            Street = "Auf dem Blahnenhof 12a"
                        },
                        new
                        {
                            Id = 43,
                            City = "Nord Luisstadt",
                            Country = "Deutschland",
                            IsDeleted = false,
                            PostalCode = "18089",
                            State = "Thüringen",
                            Street = "Saarstr. 61b"
                        },
                        new
                        {
                            Id = 44,
                            City = "Alishaland",
                            Country = "Deutschland",
                            IsDeleted = false,
                            PostalCode = "88375",
                            State = "Mecklenburg-Vorpommern",
                            Street = "In der Wüste 00c"
                        },
                        new
                        {
                            Id = 45,
                            City = "Süd Melisland",
                            Country = "Deutschland",
                            IsDeleted = false,
                            PostalCode = "84178",
                            State = "Nordrhein-Westfalen",
                            Street = "Concordiastr. 580"
                        },
                        new
                        {
                            Id = 46,
                            City = "Lawsland",
                            Country = "Deutschland",
                            IsDeleted = false,
                            PostalCode = "13241",
                            State = "Rheinland-Pfalz",
                            Street = "Unstrutstr. 9"
                        },
                        new
                        {
                            Id = 47,
                            City = "Baarckscheid",
                            Country = "Deutschland",
                            IsDeleted = false,
                            PostalCode = "19983",
                            State = "Nordrhein-Westfalen",
                            Street = "Leipziger Str. 46a"
                        },
                        new
                        {
                            Id = 48,
                            City = "Süd Rania",
                            Country = "Deutschland",
                            IsDeleted = false,
                            PostalCode = "96450",
                            State = "Thüringen",
                            Street = "Flensburger Str. 85b"
                        },
                        new
                        {
                            Id = 49,
                            City = "Nord Micheldorf",
                            Country = "Deutschland",
                            IsDeleted = false,
                            PostalCode = "92643",
                            State = "Saarland",
                            Street = "Alfred-Kubin-Str. 338"
                        },
                        new
                        {
                            Id = 50,
                            City = "Süd Ian",
                            Country = "Deutschland",
                            IsDeleted = false,
                            PostalCode = "50492",
                            State = "Saarland",
                            Street = "Niederblecher 72"
                        });
                });

            modelBuilder.Entity("proAdministration.Data.Entities.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AddressId")
                        .HasColumnType("int");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("CustomerId")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("AddressId");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AddressId = 1,
                            Currency = "EUR",
                            CustomerId = "214-764391",
                            Email = "business_zender28@banse-giesche.de",
                            IsDeleted = false,
                            Name = "Banse - Giesche",
                            PhoneNumber = "+49-779-0137173"
                        },
                        new
                        {
                            Id = 2,
                            AddressId = 2,
                            Currency = "EUR",
                            CustomerId = "741-913842",
                            Email = "business.lamos@scherer-gmbh.de",
                            IsDeleted = false,
                            Name = "Scherer GmbH",
                            PhoneNumber = "+49-270-0337886"
                        },
                        new
                        {
                            Id = 3,
                            AddressId = 3,
                            Currency = "EUR",
                            CustomerId = "268-151293",
                            Email = "info90@kúhnert-schwarzmeier.de",
                            IsDeleted = false,
                            Name = "Kúhnert - Schwarzmeier",
                            PhoneNumber = "(0874) 254094553"
                        },
                        new
                        {
                            Id = 4,
                            AddressId = 4,
                            Currency = "EUR",
                            CustomerId = "895-400644",
                            Email = "hr_schneider@geissler-metzner-and-jamrozy.de",
                            IsDeleted = false,
                            Name = "Geissler, Metzner and Jamrozy",
                            PhoneNumber = "(07838) 6400316"
                        },
                        new
                        {
                            Id = 5,
                            AddressId = 5,
                            Currency = "EUR",
                            CustomerId = "322-649195",
                            Email = "business.bormann@wittl-gruppe.de",
                            IsDeleted = false,
                            Name = "Wittl Gruppe",
                            PhoneNumber = "+49-0824-08717279"
                        },
                        new
                        {
                            Id = 6,
                            AddressId = 6,
                            Currency = "EUR",
                            CustomerId = "859-898547",
                            Email = "info77@riedel-dobbrunz.de",
                            IsDeleted = false,
                            Name = "Riedel - Dobbrunz",
                            PhoneNumber = "(07866) 3012304"
                        },
                        new
                        {
                            Id = 7,
                            AddressId = 7,
                            Currency = "EUR",
                            CustomerId = "386-036098",
                            Email = "business_stuermer@koderisch-voelkel-and-knorscheidt.de",
                            IsDeleted = false,
                            Name = "Koderisch, Voelkel and Knorscheidt",
                            PhoneNumber = "(08075) 1430904"
                        },
                        new
                        {
                            Id = 8,
                            AddressId = 8,
                            Currency = "EUR",
                            CustomerId = "913-285449",
                            Email = "business.niedermeier@esenwein-gmbh-co-kg.de",
                            IsDeleted = false,
                            Name = "Esenwein GmbH & Co. KG",
                            PhoneNumber = "(0984) 883846867"
                        },
                        new
                        {
                            Id = 9,
                            AddressId = 9,
                            Currency = "EUR",
                            CustomerId = "440-424990",
                            Email = "info65@unger-kustermann.de",
                            IsDeleted = false,
                            Name = "Unger - Kustermann",
                            PhoneNumber = "+49-597-0051536"
                        },
                        new
                        {
                            Id = 10,
                            AddressId = 10,
                            Currency = "EUR",
                            CustomerId = "977-672342",
                            Email = "info6@pfersich-gröss-and-lack.de",
                            IsDeleted = false,
                            Name = "Pfersich, Gröss and Lack",
                            PhoneNumber = "(0911) 365695831"
                        },
                        new
                        {
                            Id = 11,
                            AddressId = 11,
                            Currency = "EUR",
                            CustomerId = "404-911893",
                            Email = "business_fehrig48@kaczmarek-gmbh.de",
                            IsDeleted = false,
                            Name = "Kaczmarek GmbH",
                            PhoneNumber = "+49-9525-88763559"
                        },
                        new
                        {
                            Id = 12,
                            AddressId = 12,
                            Currency = "EUR",
                            CustomerId = "931-160244",
                            Email = "info_jambor@dautzenberg-sievers-and-stürmer.de",
                            IsDeleted = false,
                            Name = "Dautzenberg, Sievers and Stürmer",
                            PhoneNumber = "(00947) 0282218"
                        },
                        new
                        {
                            Id = 13,
                            AddressId = 13,
                            Currency = "EUR",
                            CustomerId = "568-309795",
                            Email = "hr14@storl-gmbh-co-kg.de",
                            IsDeleted = false,
                            Name = "Storl GmbH & Co. KG",
                            PhoneNumber = "(00035) 0159817"
                        },
                        new
                        {
                            Id = 14,
                            AddressId = 14,
                            Currency = "EUR",
                            CustomerId = "095-557147",
                            Email = "business_sander74@moser-kahl.de",
                            IsDeleted = false,
                            Name = "Moser - Kahl",
                            PhoneNumber = "+49-076-2390593"
                        },
                        new
                        {
                            Id = 15,
                            AddressId = 15,
                            Currency = "EUR",
                            CustomerId = "522-796698",
                            Email = "business.kroeger@hirschberg-emmelmann-and-walther.de",
                            IsDeleted = false,
                            Name = "Hirschberg, Emmelmann and Walther",
                            PhoneNumber = "(00185) 5211896"
                        },
                        new
                        {
                            Id = 16,
                            AddressId = 16,
                            Currency = "EUR",
                            CustomerId = "059-945049",
                            Email = "hr2@brandt-ohg.de",
                            IsDeleted = false,
                            Name = "Brandt OHG",
                            PhoneNumber = "+49-915-9766286"
                        },
                        new
                        {
                            Id = 17,
                            AddressId = 17,
                            Currency = "EUR",
                            CustomerId = "686-184590",
                            Email = "business_heinke0@schäning-ruth.de",
                            IsDeleted = false,
                            Name = "Schäning - Ruth",
                            PhoneNumber = "+49-180-0893452"
                        },
                        new
                        {
                            Id = 18,
                            AddressId = 18,
                            Currency = "EUR",
                            CustomerId = "103-432942",
                            Email = "info42@lukoschek-leide-and-agostini.de",
                            IsDeleted = false,
                            Name = "Lukoschek, Leide and Agostini",
                            PhoneNumber = "(0122) 203414855"
                        },
                        new
                        {
                            Id = 19,
                            AddressId = 19,
                            Currency = "EUR",
                            CustomerId = "630-671493",
                            Email = "info89@hackelbusch-gruppe.de",
                            IsDeleted = false,
                            Name = "Hackelbusch Gruppe",
                            PhoneNumber = "+49-7163-52657247"
                        },
                        new
                        {
                            Id = 20,
                            AddressId = 20,
                            Currency = "EUR",
                            CustomerId = "167-820844",
                            Email = "hr_streit26@balck-brehmer.de",
                            IsDeleted = false,
                            Name = "Balck - Brehmer",
                            PhoneNumber = "(02047) 3063100"
                        },
                        new
                        {
                            Id = 21,
                            AddressId = 21,
                            Currency = "EUR",
                            CustomerId = "694-069395",
                            Email = "business.just68@schembera-ohg.de",
                            IsDeleted = false,
                            Name = "Schembera OHG",
                            PhoneNumber = "(0246) 053709639"
                        },
                        new
                        {
                            Id = 22,
                            AddressId = 22,
                            Currency = "EUR",
                            CustomerId = "221-217746",
                            Email = "info_taechl@könig-oeser.de",
                            IsDeleted = false,
                            Name = "König - Oeser",
                            PhoneNumber = "(0628) 727786836"
                        },
                        new
                        {
                            Id = 23,
                            AddressId = 23,
                            Currency = "EUR",
                            CustomerId = "758-456298",
                            Email = "hr_brehmer@gehring-kinzy-and-knorr.de",
                            IsDeleted = false,
                            Name = "Gehring, Kinzy and Knorr",
                            PhoneNumber = "(02284) 8093798"
                        },
                        new
                        {
                            Id = 24,
                            AddressId = 24,
                            Currency = "EUR",
                            CustomerId = "285-605649",
                            Email = "business.welsch95@wischer-ag.de",
                            IsDeleted = false,
                            Name = "Wischer AG",
                            PhoneNumber = "+49-3607-04095514"
                        },
                        new
                        {
                            Id = 25,
                            AddressId = 25,
                            Currency = "EUR",
                            CustomerId = "712-844190",
                            Email = "info_krohn@rheder-zahn.de",
                            IsDeleted = false,
                            Name = "Rheder - Zahn",
                            PhoneNumber = "(04391) 9271641"
                        },
                        new
                        {
                            Id = 26,
                            AddressId = 26,
                            Currency = "EUR",
                            CustomerId = "349-192541",
                            Email = "info79@kochan-schersing-and-küter.de",
                            IsDeleted = false,
                            Name = "Kochan, Schersing and Küter",
                            PhoneNumber = "(0332) 231222770"
                        },
                        new
                        {
                            Id = 27,
                            AddressId = 27,
                            Currency = "EUR",
                            CustomerId = "876-331093",
                            Email = "business_laux21@erm-kg.de",
                            IsDeleted = false,
                            Name = "Erm KG",
                            PhoneNumber = "+49-474-4543814"
                        },
                        new
                        {
                            Id = 28,
                            AddressId = 28,
                            Currency = "EUR",
                            CustomerId = "303-580444",
                            Email = "info_bayer@ullrich-hermecke.de",
                            IsDeleted = false,
                            Name = "Ullrich - Hermecke",
                            PhoneNumber = "+49-341-5778450"
                        },
                        new
                        {
                            Id = 29,
                            AddressId = 29,
                            Currency = "EUR",
                            CustomerId = "830-729895",
                            Email = "hr5@petzold-büchele-and-martel.de",
                            IsDeleted = false,
                            Name = "Petzold, Büchele and Martel",
                            PhoneNumber = "+49-4569-81518654"
                        },
                        new
                        {
                            Id = 30,
                            AddressId = 30,
                            Currency = "EUR",
                            CustomerId = "367-977346",
                            Email = "business_bozsik47@jungbluth-tasche.de",
                            IsDeleted = false,
                            Name = "Jungbluth - Tasche",
                            PhoneNumber = "+49-498-2056872"
                        },
                        new
                        {
                            Id = 31,
                            AddressId = 31,
                            Currency = "EUR",
                            CustomerId = "994-126798",
                            Email = "hr_prediger@dauer-plotzitzka-and-wallstab.de",
                            IsDeleted = false,
                            Name = "Dauer, Plotzitzka and Wallstab",
                            PhoneNumber = "(0539) 428745810"
                        },
                        new
                        {
                            Id = 32,
                            AddressId = 32,
                            Currency = "EUR",
                            CustomerId = "421-365249",
                            Email = "hr.clarius@stifel-kg.de",
                            IsDeleted = false,
                            Name = "Stifel KG",
                            PhoneNumber = "(08570) 6428145"
                        },
                        new
                        {
                            Id = 33,
                            AddressId = 33,
                            Currency = "EUR",
                            CustomerId = "958-613690",
                            Email = "business63@mordhorst-ganzmann.de",
                            IsDeleted = false,
                            Name = "Mordhorst - Ganzmann",
                            PhoneNumber = "+49-450-2955973"
                        },
                        new
                        {
                            Id = 34,
                            AddressId = 34,
                            Currency = "EUR",
                            CustomerId = "475-852141",
                            Email = "business15@hingst-alexander-and-ade.de",
                            IsDeleted = false,
                            Name = "Hingst, Alexander and Ade",
                            PhoneNumber = "(0543) 179031794"
                        },
                        new
                        {
                            Id = 35,
                            AddressId = 35,
                            Currency = "EUR",
                            CustomerId = "002-001503",
                            Email = "info_poser@bozsik-ug.de",
                            IsDeleted = false,
                            Name = "Bozsik UG",
                            PhoneNumber = "+49-668-4492100"
                        },
                        new
                        {
                            Id = 36,
                            AddressId = 36,
                            Currency = "EUR",
                            CustomerId = "539-240054",
                            Email = "hr51@schäfer-mathiszik.de",
                            IsDeleted = false,
                            Name = "Schäfer - Mathiszik",
                            PhoneNumber = "+49-3626-60626894"
                        },
                        new
                        {
                            Id = 37,
                            AddressId = 37,
                            Currency = "EUR",
                            CustomerId = "066-498405",
                            Email = "info41@loy-honz-and-bohge.de",
                            IsDeleted = false,
                            Name = "Loy, Honz and Bohge",
                            PhoneNumber = "+49-6679-29337678"
                        },
                        new
                        {
                            Id = 38,
                            AddressId = 38,
                            Currency = "EUR",
                            CustomerId = "593-637956",
                            Email = "info_geissler@haaf-gmbh.de",
                            IsDeleted = false,
                            Name = "Haaf GmbH",
                            PhoneNumber = "+49-5708-14349620"
                        },
                        new
                        {
                            Id = 39,
                            AddressId = 39,
                            Currency = "EUR",
                            CustomerId = "120-886308",
                            Email = "hr38@bahl-tächl.de",
                            IsDeleted = false,
                            Name = "Bahl - Tächl",
                            PhoneNumber = "(01749) 4565648"
                        },
                        new
                        {
                            Id = 40,
                            AddressId = 40,
                            Currency = "EUR",
                            CustomerId = "657-025859",
                            Email = "business.gutschank67@schedler-gmbh-co-kg.de",
                            IsDeleted = false,
                            Name = "Schedler GmbH & Co. KG",
                            PhoneNumber = "+49-7816-70623452"
                        },
                        new
                        {
                            Id = 41,
                            AddressId = 41,
                            Currency = "EUR",
                            CustomerId = "184-373200",
                            Email = "info_schulze9@köhrbrück-krol.de",
                            IsDeleted = false,
                            Name = "Köhrbrück - Krol",
                            PhoneNumber = "(07129) 9378108"
                        },
                        new
                        {
                            Id = 42,
                            AddressId = 42,
                            Currency = "EUR",
                            CustomerId = "611-512751",
                            Email = "business51@gebhardt-gotz-and-küsters.de",
                            IsDeleted = false,
                            Name = "Gebhardt, Gotz and Küsters",
                            PhoneNumber = "(0853) 107850719"
                        },
                        new
                        {
                            Id = 43,
                            AddressId = 43,
                            Currency = "EUR",
                            CustomerId = "148-761102",
                            Email = "business88@winkelmann-gmbh.de",
                            IsDeleted = false,
                            Name = "Winkelmann GmbH",
                            PhoneNumber = "+49-6895-32091934"
                        },
                        new
                        {
                            Id = 44,
                            AddressId = 44,
                            Currency = "EUR",
                            CustomerId = "775-900654",
                            Email = "info_hudak35@reus-schönebeck.de",
                            IsDeleted = false,
                            Name = "Reus - Schönebeck",
                            PhoneNumber = "(08366) 4408797"
                        },
                        new
                        {
                            Id = 45,
                            AddressId = 45,
                            Currency = "EUR",
                            CustomerId = "202-158005",
                            Email = "info77@knorscheidt-mohr-and-marquart.de",
                            IsDeleted = false,
                            Name = "Knorscheidt, Mohr and Marquart",
                            PhoneNumber = "+49-8778-57146593"
                        },
                        new
                        {
                            Id = 46,
                            AddressId = 46,
                            Currency = "EUR",
                            CustomerId = "739-397556",
                            Email = "business75@erdmann-gruppe.de",
                            IsDeleted = false,
                            Name = "Erdmann Gruppe",
                            PhoneNumber = "(0591) 917121412"
                        },
                        new
                        {
                            Id = 47,
                            AddressId = 47,
                            Currency = "EUR",
                            CustomerId = "266-546907",
                            Email = "info.umlauft61@uhrig-duma.de",
                            IsDeleted = false,
                            Name = "Uhrig - Duma",
                            PhoneNumber = "(0950) 394373859"
                        },
                        new
                        {
                            Id = 48,
                            AddressId = 48,
                            Currency = "EUR",
                            CustomerId = "893-885459",
                            Email = "hr3@paukner-wakan-and-newton.de",
                            IsDeleted = false,
                            Name = "Paukner, Wakan and Newton",
                            PhoneNumber = "+49-9916-18432487"
                        },
                        new
                        {
                            Id = 49,
                            AddressId = 49,
                            Currency = "EUR",
                            CustomerId = "310-033800",
                            Email = "business63@jossa-rittweg.de",
                            IsDeleted = false,
                            Name = "Jossa - Rittweg",
                            PhoneNumber = "(03023) 8215000"
                        },
                        new
                        {
                            Id = 50,
                            AddressId = 50,
                            Currency = "EUR",
                            CustomerId = "847-272351",
                            Email = "hr88@danner-kühnel-and-adam.de",
                            IsDeleted = false,
                            Name = "Danner, Kühnel and Adam",
                            PhoneNumber = "+49-0641-44669633"
                        });
                });

            modelBuilder.Entity("proAdministration.Data.Entities.Customer", b =>
                {
                    b.HasOne("proAdministration.Data.Entities.Address", "Address")
                        .WithMany()
                        .HasForeignKey("AddressId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Address");
                });
#pragma warning restore 612, 618
        }
    }
}
